feat: add subplots
invia-flights/blitzly pull request #21
Opened 2022-12-27 12:31 UTC by premsrii

Create subplots using figure objects instead of traces.

2022-12-27 13:09 UTC, chrislemke requested changes

2022-12-27 13:09 UTC, chrislemke commented on src/blitzly/subplots/subplots.py
> +    subfig_list: List,
The type of entry of List is missing. Should be something like `List[BaseFigure]`

2022-12-27 13:09 UTC, chrislemke commented on src/blitzly/subplots/subplots.py
> +        subfig_list (List): A list of figure objects.
Please also adjust the type of `subfig_list` here.

2022-12-27 13:09 UTC, chrislemke commented on src/blitzly/subplots/subplots.py
> +        show (Optional[bool]): Whether to show the figure.
`show` is not optional.

Maybe you can fix it in the other modules too?

2022-12-27 13:09 UTC, chrislemke commented on src/blitzly/subplots/subplots.py
> +    subfig_traces: List = [[] for _ in subfig_list]
Personally a would prefer `[[]] * len(subfig_list)`

2022-12-27 13:31 UTC, premsrii commented on src/blitzly/subplots/subplots.py
> +    subfig_traces: List = [[] for _ in subfig_list]
The suggested solution wouldn't work.

2022-12-27 13:42 UTC, chrislemke commented on src/blitzly/subplots/subplots.py
> +    subfig_traces: List = [[] for _ in subfig_list]
Why not?

2022-12-27 13:55 UTC, chrislemke commented
Concerning the following commits:
fix: docstrings for argument
fix: skip subplots directory in imports

For squashing the commits those names are acceptable. But keep in mind `fix` is reserved for bug fixing and would appear under `Bug Fix` in the change log.

2022-12-27 14:22 UTC, premsrii commented on src/blitzly/subplots/subplots.py
> +    subfig_traces: List = [[] for _ in subfig_list]
They are equal because they are empty. The former returns three references. The latter returns the same reference thrice.

Your suggestion:
```
>>> same_ref = [[1]] * 3
>>> same_ref
[[1], [1], [1]]
>>> same_ref[0][0] = 2
>>> same_ref
[[2], [2], [2]]
```

Current solution:
```
>>> diff_ref = [[] for _ in range(3)]
>>> diff_ref = [[1] for _ in range(3)]
>>> diff_ref
[[1], [1], [1]]
>>> diff_ref[0][0] = 2
>>> diff_ref
[[2], [1], [1]]
```

2022-12-27 14:25 UTC, premsrii commented on src/blitzly/subplots/subplots.py
> +    subfig_traces: List = [[] for _ in subfig_list]
Since the list is empty, the type has to be provided. Else `mypy` would throw the following error:
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/blitzly/subplots/subplots.py:48: error: Need type annotation for "subfig_traces"  [var-annotated]
```

2022-12-27 14:40 UTC, chrislemke requested changes

2022-12-27 14:40 UTC, chrislemke commented on src/blitzly/subplots/subplots.py
> +    subfig_traces: List = [[] for _ in subfig_list]
Please add a specific List type like `List[str]`. Thanks!

2022-12-27 15:24 UTC, chrislemke requested changes

2022-12-27 15:24 UTC, chrislemke commented on src/blitzly/subplots/__init__.py
> +from .subplots import make_subplots
This feels like a hack 🙃

The project structure stays exactly the same. You just add a init file. 
What I meant with my earlier message is, that having a folder `subplots` with a module `subplots` with a function `make_subplots` just not feels like a clean and elegant solution. When creating the project structure could help to understand what the next steps could be. E.g.: Which other module could be in the `subplots` folder? If there is only going to be one module in that folder. Is that folder needed? 

I hope you get my point.

2022-12-28 08:36 UTC, chrislemke requested changes

2022-12-28 08:36 UTC, chrislemke commented on src/blitzly/subplots.py
> +    Creates subplots using a provided list of figure objects.
There is a docstring but this function does not appear in the documentation. 📒

2022-12-28 09:34 UTC, chrislemke requested changes

2022-12-28 09:34 UTC, chrislemke commented on pyproject.toml
> +    "R0801",
Please don't add this to the exceptions. We should not have duplicated code in the project. Instead, you could either fix the duplication or add an exception for the code you added.

2022-12-28 09:34 UTC, chrislemke commented on docs/README.md
> +
Nice! Maybe it also makes sense to add the example in the Usage section of the readme and in the playground notebook. What do you think?

2022-12-28 15:40 UTC, chrislemke approved these changes

2022-12-28 15:57 UTC, merged