feat: add slope plots
invia-flights/blitzly pull request #38
Opened 2023-01-03 16:06 UTC by premsrii

This PR adds a new type of plot called the [slope plots](https://datavizproject.com/data-type/slope-chart/) They are very similar to dumbbell plots, and are used to compare two sets of data.

![newplot](https://user-images.githubusercontent.com/5824907/210395037-70af7e93-37a6-407c-b843-4cbcb7ed439a.png)

2023-01-03 16:32 UTC, chrislemke requested changes

2023-01-04 08:40 UTC, chrislemke approved these changes

2023-01-04 08:40 UTC, chrislemke commented on tests/conftest.py
> +def X_numbers_two_column() -> pd.DataFrame:
This is a nice solution but - in my opinion - you could also have added a pylint disable rule - since it is just in the test module.

2023-01-04 08:43 UTC, chrislemke requested changes

2023-01-04 08:46 UTC, premsrii commented on src/blitzly/plots/slope.py
> +        data = pd.DataFrame(data)
That is a good idea. But it causes quite a bit of refactoring, because some tests would fail, and I have to add an extra test. I think it is better I do it in the next PR.

2023-01-04 08:52 UTC, premsrii commented on src/blitzly/plots/slope.py
> +                mode="markers+lines+text",
I would vote against it, because these plots are meant to look this way.

2023-01-04 09:00 UTC, chrislemke commented on src/blitzly/plots/slope.py
> +        data = pd.DataFrame(data)
Good point!

2023-01-04 09:00 UTC, premsrii commented on tests/conftest.py
> +def X_numbers_two_column() -> pd.DataFrame:
I thought about it too. But I didn't know if it is good practise. Let me know which way you prefer.

2023-01-04 09:01 UTC, chrislemke approved these changes

2023-01-04 09:01 UTC, premsrii commented on .pre-commit-config.yaml
> +            "--with",
I always got the deprecation error with `--dev`. That's way I changed it.

2023-01-04 09:06 UTC, merged